package frames;

import dao.DaoGraficos;
import entity.DataGraficos;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;



public class JDialogGraficos extends javax.swing.JDialog {

    DaoGraficos daoGraficos = new DaoGraficos();
    List<DataGraficos> cliente;
    
    public JDialogGraficos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        
       
            cliente = daoGraficos.getCliente("1");
            cliente = daoGraficos.getCliente("2");
            cliente = daoGraficos.getCliente("3");
            cliente = daoGraficos.getCliente("4");
            cliente = daoGraficos.getCliente("5");
            cliente = daoGraficos.getCliente("6");
            cliente = daoGraficos.getCliente("7");
            cliente = daoGraficos.getCliente("8");
            cliente = daoGraficos.getCliente("9");
            cliente = daoGraficos.getCliente("10");
            cliente = daoGraficos.getCliente("11");
            cliente = daoGraficos.getCliente("12");
            
            
        
        
        DefaultCategoryDataset d = new DefaultCategoryDataset();
        d.setValue(cliente.get(0).getJan(), "JAN", "JAN");
        d.setValue(cliente.get(0).getFev(), "FEV", "FEV");
        d.setValue(cliente.get(0).getMar(), "MAR", "MAR");
        d.setValue(cliente.get(0).getAbr(), "ABR", "ABR");
        d.setValue(cliente.get(0).getMai(), "MAI", "MAI");
        d.setValue(cliente.get(0).getJun(), "JUN", "JUN");
        d.setValue(cliente.get(0).getJul(), "JUL", "JUL");
        d.setValue(cliente.get(0).getAgo(), "AGO", "AGO");
        d.setValue(cliente.get(0).getSet(), "SET", "SET");
        d.setValue(cliente.get(0).getOut(), "OUT", "OUT");
        d.setValue(cliente.get(0).getNov(), "NOV", "NOV");
        d.setValue(cliente.get(0).getDez(), "DEZ", "DEZ");
        JFreeChart g = ChartFactory.createBarChart3D("ANUAL", "f", "uttt", d, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel f = new ChartPanel(g);

        jPanel1.add(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGraficos dialog = new JDialogGraficos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
